//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Messages", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} không hợp lệ..
        /// </summary>
        internal static string E_MSG_00001 {
            get {
                return ResourceManager.GetString("E_MSG_00001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} không tồn tại..
        /// </summary>
        internal static string E_MSG_00002 {
            get {
                return ResourceManager.GetString("E_MSG_00002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} sẳn sàng tồn tại..
        /// </summary>
        internal static string E_MSG_00003 {
            get {
                return ResourceManager.GetString("E_MSG_00003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} không được để trống..
        /// </summary>
        internal static string E_MSG_00004 {
            get {
                return ResourceManager.GetString("E_MSG_00004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} đã xóa..
        /// </summary>
        internal static string E_MSG_00005 {
            get {
                return ResourceManager.GetString("E_MSG_00005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} còn tồn tại..
        /// </summary>
        internal static string E_MSG_00006 {
            get {
                return ResourceManager.GetString("E_MSG_00006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} không được phép cập nhật..
        /// </summary>
        internal static string E_MSG_00007 {
            get {
                return ResourceManager.GetString("E_MSG_00007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên người dùng hoặc mật khẩu không đúng..
        /// </summary>
        internal static string E_MSG_00008 {
            get {
                return ResourceManager.GetString("E_MSG_00008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} không đúng..
        /// </summary>
        internal static string E_MSG_00009 {
            get {
                return ResourceManager.GetString("E_MSG_00009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} phải lớn hơn 0..
        /// </summary>
        internal static string E_MSG_00011 {
            get {
                return ResourceManager.GetString("E_MSG_00011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [F.MSG.00001] Không thể để kết nối với máy chủ cơ sở dữ liệu với các thiết lập đang được cung cấp..
        /// </summary>
        internal static string F_MSG_00001 {
            get {
                return ResourceManager.GetString("F_MSG_00001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi kết nối cơ sở dữ liệu..
        /// </summary>
        internal static string F_MSG_00001_H {
            get {
                return ResourceManager.GetString("F_MSG_00001_H", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi cơ sở dữ liệu.
        /// </summary>
        internal static string F_MSG_00001_T {
            get {
                return ResourceManager.GetString("F_MSG_00001_T", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [F.MSG.00002] Kết nối đến máy chủ mail thất bại..
        /// </summary>
        internal static string F_MSG_00002 {
            get {
                return ResourceManager.GetString("F_MSG_00002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi kết nối máy chủ mail..
        /// </summary>
        internal static string F_MSG_00002_H {
            get {
                return ResourceManager.GetString("F_MSG_00002_H", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi hệ thống..
        /// </summary>
        internal static string F_MSG_00002_T {
            get {
                return ResourceManager.GetString("F_MSG_00002_T", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thành công..
        /// </summary>
        internal static string I_MSG_00001 {
            get {
                return ResourceManager.GetString("I_MSG_00001", resourceCulture);
            }
        }
    }
}
